language: go
go: '1.12.x'
git:
  depth: 1
env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
services:
  - docker
jobs:
  include:
    - stage: "Test"
      script: |
        make build && cd ./bin && \
        ./armada create clusters --calico --tiller && \
        ./armada create clusters -n 3 --image kindest/node:v1.14.6 --weave --tiller && \
        ./armada create clusters -n 5 --flannel --image kindest/node:v1.13.10 --tiller --overlap && \
        ./armada destroy clusters --cluster cl2,cl5 && \
        ./armada destroy clusters
      name: "local test"
    - script: |
        make docker-build && \
        make docker-run ARGS="./armada create clusters --calico --tiller" && \
        make docker-run ARGS="./armada create clusters -n 3 --image kindest/node:v1.14.6 --weave --tiller" && \
        make docker-run ARGS="./armada create clusters -n 5 --flannel --image kindest/node:v1.13.10 --tiller --overlap" && \
        make docker-run ARGS="./armada destroy clusters --cluster cl2,cl5" && \
        make docker-run ARGS="./armada destroy clusters"
      name: "docker test"
    - stage: "Release"
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: curl -sL https://git.io/goreleaser | bash
        on:
          tags: true
          condition: $TRAVIS_OS_NAME = linux