language: go
go: '1.12.x'
git:
  depth: 1
env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
    - TERM=dumb
services:
  - docker
jobs:
  include:
    - stage: "Test"
      script: make build && make test && make e2e
      name: "local test"
    - script: |
        make build && \
        make docker-run ARGS="./armada create clusters -n 2 --flannel --overlap -v" && \
        make docker-run ARGS="./armada create clusters -n 3 --weave --tiller --image kindest/node:v1.14.9 -v" && \
        make docker-run ARGS="./armada create clusters -n 4 --calico -v" && \
        make docker-run ARGS="./armada destroy clusters --cluster cl1,cl3" && \
        make docker-run ARGS="./armada destroy clusters"
      name: "docker test"
    - stage: "Release"
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: curl -sL https://git.io/goreleaser | bash
        on:
          tags: true
          condition: $TRAVIS_OS_NAME = linux
